pipeline {
    agent any
    stages {
        stage('Prepare') {
            git 'https://github.com/VyacheslavKazakov/simple-java-maven-app.git'
        }
        stage('Build') {
            steps {
                tool name: 'mvn', type: 'maven'
            }
        }
        stage('Reports') {
            steps {
                junit 'target/surefire-reports/*.xml'
            }
        }
        stage('Coverage') {
            steps {
                jacoco()
            }
        }
    }
}
