pipeline {
    agent any
    stages {
        stage('Prepare') {
            steps {
                git 'https://github.com/VyacheslavKazakov/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                tool name: 'mvn', type: 'maven'
                sh '../../tools/hudson.tasks.Maven_MavenInstallation/mvn/bin/mvn verify'
            }
        }
        stage('Reports') {
            steps {
                junit 'target/surefire-reports/*.xml'
            }
        }
        stage('Coverage') {
            steps {
                jacoco()
            }
        }
        stage('Archive') {
            steps {
                archive 'my-app-1.0-SNAPSHOT.jar'
            }
        }
    }
}
